### ISSUE TITLE
bug when trying to pull tags

### ISSUE THREAD

**Issue by nicofarr** [r03ert0/cmtool#1]
Hi, 

when trying 

./cmtool /Volumes/SubthalamicNucleus/Recherche/coactivationmap/cmap13 -tag affect -convert lr -out ~/Desktop/ -save map

I get a segfault... 

Am I missing something ? Does the option -tag have to be combined with something else ? 

Nico

**Comment by r03ert0** [comment]
Hi Nicolas,

You have to provide first of all the seed for making a coactivation map!
This is an example command for saving the top tags:

./cmtool $dir/coincidences2013 -vol 6,24,23 -convert phir -out ~/Desktop/
-save topmesh

it will save to the Desktop a file called top100.0.txt with the 100 tags
that correlate the most with the coactivation map with seed 6,24,23 (in
voxel coordinates). This is the beginning of the resulting file:

R2    MeshCode
0.358088    Motor Skills
0.325081    Touch Perception
0.321242    Imitative Behavior
0.304931    Pitch Discrimination
0.304052    Imagination
0.301811    Psychophysics
0.299863    Sound Localization
...

The 1st column is the R2 (variance captured by the correlation), and the
2nd column is the MeSH name.

One important thing with cmtool is that the arguments are read
sequentially, like a script. It is important then, for example, to define
the output file (-out ~/Desktop/) BEFORE saving the results (the "-save
topmesh" part), or to have defined the seed of the coactivation map (-vol
6,24,23) before converting it to correlations (-convert phir).

Now, instead of just getting the top 100 tags, you can also pull all the
papers that constitute a specific map, with their tags. This is an example
command:

./cmtool $dir/coincidences2013 -vol 6,24,23 -convert phir -out ~/Desktop/
-save articles 0.1 4

This is the result (first lines):

Peaks    Percent    ExpNumber    PubMedID    Reference    MeshCodes
Domains
1    12.5    1    15858160    "Abe N, 2006"    F01.145.813.157;F03.300
1    12.5    3    18372290    "Abe N, 2008"
F01.145.813.157;F02.463.785.626;F02.463.425.540;F02.463.425.540.706;F01.393.821

1    12.5    11    19015036    "Abel S, 2009"
F02.463.188;F01.525.200.310
1    12.5    12    16487726    "Abler B, 2006"
F02.463.425.234;F01.470;F01.658.370;F02.463.425.770.836
1    12.5    13    17947346    "Abutalebi J, 2008"    F02.463.188
2    25    14    17947346    "Abutalebi J, 2008"    F02.463.188
3    37.5    15    17947346    "Abutalebi J, 2008"    F02.463.188
1    12.5    17    15670688    "Achim AM, 2005"
F04.754.720.346;F02.463.425.540;F02.463.425.540.706
1    12.5    18    15670688    "Achim AM, 2005"
F04.754.720.346;F02.463.425.540;F02.463.425.540.706
...

The MeSH descriptors are organised as a tree. Each descriptor has a code
and an equivalent name. By default, cmtool displays the codes. The codes
start with a character, for example A for the codes related to anatomy,  F
for those related to psychiatry and Psychology, or C for diseases. By
default, cmtool will display only the descriptors in the F category (check
http://www.nlm.nih.gov/cgi/mesh/2014/MB_cgi). It is possible though to
filter them otherwise using the "-meshfilter    root", where you change
"root" by the root of the codes you want to select. For example, within F,
all mental disorders are under "F03". Then, if you wanted to have the top
100 mental disorders correlated with the coactivation map with seed
6,24,23, you should write:

./cmtool $dir/coincidences2013 -vol 6,24,23 -convert phir -out ~/Desktop/
-meshfilter F03 -save articles 0.1 4

which produces:

Peaks    Percent    ExpNumber    PubMedID    Reference    MeshCodes
Domains
1    12.5    1    15858160    "Abe N, 2006"    F03.300
1    12.5    3    18372290    "Abe N, 2008"
1    12.5    11    19015036    "Abel S, 2009"
1    12.5    12    16487726    "Abler B, 2006"
1    12.5    13    17947346    "Abutalebi J, 2008"
2    25    14    17947346    "Abutalebi J, 2008"
3    37.5    15    17947346    "Abutalebi J, 2008"
1    12.5    17    15670688    "Achim AM, 2005"
1    12.5    18    15670688    "Achim AM, 2005"
1    12.5    20    17023179    "Addis DR, 2006"
2    25    21    17023179    "Addis DR, 2006"
1    12.5    22    19703572    "Adolph O, 2010"
1    12.5    23    19703572    "Adolph O, 2010"
1    12.5    26    20394829    "Agam Y, 2010"    F03.550.325
...

You can also choose to display names instead of codes using

./cmtool $dir/coincidences2013 -vol 6,24,23 -convert phir -out ~/Desktop/
-meshfilter F03 -meshdisplay names -save articles 0.1 4

which produces:

Peaks    Percent    ExpNumber    PubMedID    Reference    MeshCodes
Domains
1    12.5    1    15858160    "Abe N, 2006"    Dissociative Disorders
1    12.5    3    18372290    "Abe N, 2008"
1    12.5    11    19015036    "Abel S, 2009"
1    12.5    12    16487726    "Abler B, 2006"
1    12.5    13    17947346    "Abutalebi J, 2008"
2    25    14    17947346    "Abutalebi J, 2008"
3    37.5    15    17947346    "Abutalebi J, 2008"
1    12.5    17    15670688    "Achim AM, 2005"
1    12.5    18    15670688    "Achim AM, 2005"
1    12.5    20    17023179    "Addis DR, 2006"
2    25    21    17023179    "Addis DR, 2006"
1    12.5    22    19703572    "Adolph O, 2010"
1    12.5    23    19703572    "Adolph O, 2010"
1    12.5    26    20394829    "Agam Y, 2010"    Child Development
Disorders, Pervasive
1    12.5    29    16337813    "Aichhorn M, 2006"
2    25    32    19439183    "Akitsuki Y, 2009"
1    12.5    34    19439183    "Akitsuki Y, 2009"
4    50    37    15269107    "Aleman A, 2005"
2    25    38    15269107    "Aleman A, 2005"
5    62.5    39    15238440    "Alkadhi H, 2005"
1    12.5    42    16023375    "Allen G, 2005"
1    12.5    44    19703570    "Allen P, 2010"    Psychotic Disorders
1    12.5    45    19703570    "Allen P, 2010"    Psychotic Disorders
...

In all the previous examples the coactivation map is that produced by the
seed voxel at coordinates 6,23,24, but you can use any other of the methods
to specify the seed: mni coordinates, an analyze volume, or a text file
with MNI coordinates. If you have more than one seed, you can either get
one file per seed, or make the average of all seeds (using the -average
command after the -convert command)

hope this helps!

cheers,
roberto

On Mon, Jan 20, 2014 at 12:47 AM, Nicolas Farrugia <notifications@github.com
